In [2]:
import pandas as pd

In [3]:
xls = pd.ExcelFile('тест.xlsx')
print(xls.sheet_names)

['Данные об аудитории', 'Данные АБ тестов', 'Листеры']

In [4]:
df = pd.read_excel('тест.xlsx', sheet_name='Данные об аудитории')

In [4]:
df.head()

        date                               user_id  view_adverts
0 2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1 2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2 2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3 2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4 2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [5]:
df = pd.read_excel('тест.xlsx', sheet_name='Данные АБ тестов')

In [6]:
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [7]:
df = pd.read_excel('тест.xlsx', sheet_name='Листеры')

In [8]:
df.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [11]:
mau = df['user_id'].nunique()
print(mau)

7639

In [13]:
df['date'] = pd.to_datetime(df['date'])

dau = df.groupby('date')['user_id'].nunique().reset_index()

In [15]:
print(dau)

         date  user_id
0  2023-11-01      623
1  2023-11-02      649
2  2023-11-03      573
3  2023-11-04      343
4  2023-11-05      350
5  2023-11-06      660
6  2023-11-07      629
7  2023-11-08      600
8  2023-11-09      661
9  2023-11-10      583
10 2023-11-11      354
11 2023-11-12      377
12 2023-11-13      646
13 2023-11-14      687
14 2023-11-15      690
15 2023-11-16      639
16 2023-11-17      585
17 2023-11-18      412
18 2023-11-19      378
19 2023-11-20      711
20 2023-11-21      651
21 2023-11-22      608
22 2023-11-23      632
23 2023-11-24      595
24 2023-11-25      366
25 2023-11-26      372
26 2023-11-27      589
27 2023-11-28      610
28 2023-11-29      621
29 2023-11-30      620

In [17]:
dau = dau.rename(columns={'user_id': 'DAU'})

print(dau)

         date  DAU
0  2023-11-01  623
1  2023-11-02  649
2  2023-11-03  573
3  2023-11-04  343
4  2023-11-05  350
5  2023-11-06  660
6  2023-11-07  629
7  2023-11-08  600
8  2023-11-09  661
9  2023-11-10  583
10 2023-11-11  354
11 2023-11-12  377
12 2023-11-13  646
13 2023-11-14  687
14 2023-11-15  690
15 2023-11-16  639
16 2023-11-17  585
17 2023-11-18  412
18 2023-11-19  378
19 2023-11-20  711
20 2023-11-21  651
21 2023-11-22  608
22 2023-11-23  632
23 2023-11-24  595
24 2023-11-25  366
25 2023-11-26  372
26 2023-11-27  589
27 2023-11-28  610
28 2023-11-29  621
29 2023-11-30  620

In [18]:
avg_dau = dau['DAU'].mean()
print(avg_dau)

560.4666666666667

In [19]:
df['date'] = pd.to_datetime(df['date'])

In [20]:
cohort = df[df['date'] == '2023-11-01']['user_id'].unique()

In [21]:
day1_users = df[
    (df['date'] == '2023-11-02') &
    (df['user_id'].isin(cohort))
]['user_id'].nunique()

In [22]:
retention = day1_users / len(cohort) * 100
print(retention)

26.64526484751204

In [23]:
# общее количество пользователей
total_users = df['user_id'].nunique()

# пользователи, которые смотрели объявления
users_with_views = df[df['view_adverts'] > 0]['user_id'].nunique()

# конверсия
conversion = users_with_views / total_users * 100

print(f'Conversion: {conversion:.2f}%')

Conversion: 46.31%

In [24]:
avg_views = df['view_adverts'].sum() / df['user_id'].nunique()
print(avg_views)

2.8687000916350307

In [ ]:
Promoters = 1200 / 2000 = 60%
Detractors = 500 / 2000 = 25%

Ответ: 35%

In [5]:
df = pd.read_excel('тест.xlsx', sheet_name='Листеры')

In [10]:
df['revenue'].mean()

np.float64(30.70253164556962)

In [12]:
df['age'].median()

28.0